apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rqm5gtztm-python
  janus-idp.io/tekton: rqm5gtztm-python
  backstage.io/kubernetes-id: rqm5gtztm-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rqm5gtztm-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
